[package]
name = "debridge"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
clickhouse = { version = "0.15.0", features = ["uuid", "chrono"] }
dotenvy = "0.15.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.51.1", features = ["full"] }
uuid = { version = "1.23.0", features = ["serde", "v4"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
num_cpus = "1.17.0"
tokio-util = "0.7.18"
thiserror = "2.0.18"
anyhow = "1.0.102"
reqwest = { version = "0.12", features = ["json", "gzip", "brotli"] }
solana-client = "2.2"
solana-sdk = "2.2"
solana-rpc-client-api = "2.2"
solana-transaction-status-client-types = { version = "2.3.13" }
borsh = { version = "1", features = ["derive"] }
base64 = "0.22.1"
sha2 = "0.10"
governor = "0.10.4"
nonzero_ext = "0.3"
async-trait = "0.1.89"
futures = "0.3.32"
bs58 = "0.5.1"
